### ISSUE TITLE
Positioning classes don't work

### ISSUE THREAD

**Issue by zagortenay333** [passingthru67/workspaces-to-dock#47]
The `.left`, `.top`, & `.bottom` css classes seem to have no effect while the `.right` class does. Using version from master.

**Comment by passingthru67** [comment]
Would you copy/paste an example of how you are using the classes?

**Comment by zagortenay333** [comment]
```css
/* Floating bg*/
#workspacestodockDock.right .workspace-thumbnails {
    border-image: url("../../overview-assets/workspace-bg-right.svg") 7 !important;
    /* works only here */
}

.#workspacestodockDock.left .workspace-thumbnails {
    border-image: url("../../overview-assets/workspace-bg-left.svg") 7 !important;
    
}

#workspacestodockDock.top .workspace-thumbnails {
    border-image: url("../../overview-assets/workspace-bg-top.svg") 7 !important;
}

.#workspacestodockDock.bottom .workspace-thumbnails {
    border-image: url("../../overview-assets/workspace-bg-bottom.svg") 7 !important;
    border-image: none !important;
}


/* Expanded bg */
.#workspacestodockDock.left.fullheight .workspace-thumbnails {
    border-image: url("../../overview-assets/workspace-bg-left-extended.svg") 7 !important;
}

#workspacestodockDock.right.fullheight .workspace-thumbnails {
    border-image: url("../../overview-assets/workspace-bg-right-extended.svg") 7 !important;
}

#workspacestodockDock.top.fullheight .workspace-thumbnails {
    border-image: url("../../overview-assets/workspace-bg-top-extended.svg") 7 !important;
}

.#workspacestodockDock.bottom.fullheight .workspace-thumbnails {
    border-image: url("../../overview-assets/workspace-bg-bottom-extended.svg") 7 !important;
}
```
