### ISSUE TITLE
Rounded corners issues

### ISSUE THREAD

**Issue by Tunous** [passingthru67/workspaces-to-dock#74]
### Linux Distribution version

Arch Linux
### Gnome Shell version

GNOME 3.20.2
### Gnome Shell theme

Arc Theme https://github.com/horst3180/Arc-theme
### Extension version or branch

39 from https://extensions.gnome.org/
### Description of the problem

Rounded corners are located on incorrect side when workspaces dock is moved to the left side of the screen. Also when dock is located on right side and favorites panel is set to inside there are visible empty pixels between favorites panel and workspaces dock.
### Steps to reproduce the problem

Go to the settings and set the dock to show on the left side of the screen.
### Image

http://i.imgur.com/AICg3b8.png
Notice white pixels at the very left and between workspaces/favorites.

**Comment by passingthru67** [comment]
Hi @Tunous,
Arc is one of those themes that uses svg images for the borders of the dash and workspaces panel. The only way to remove the border is to remove the border-image property that references the svg in the gnome-shell.css or in the workspaces-to-dock.css (found at ~/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/themes/default/)

Try this .. edit the workspaces-to-dock.css by adding "border-image:none;" to the following classes:
#workspacestodockDock.right.inside .workspace-thumbnails
#workspacestodockDock.left.inside .workspace-thumbnails
#workspacestodockDock.top.inside .workspace-thumbnails
#workspacestodockDock.bottom.inside .workspace-thumbnails 
#workspacestodockDock.right.fullheight .workspace-thumbnails
#workspacestodockDock.left.fullheight .workspace-thumbnails
#workspacestodockDock.top.fullheight .workspace-thumbnails
#workspacestodockDock.bottom.fullheight .workspace-thumbnails

This isn't really a permanent fix because it removes the border-image svg which gives the Arc theme it's rounded edge look. Maybe someone can write up a workspaces-to-dock.css for the Arc theme and include it as part of the theme. Please see the theme support section of the  Workspaces-To-Dock readme for more details (https://github.com/passingthru67/workspaces-to-dock#theme-support)

**Comment by Tunous** [comment]
Thanks for the information.

I managed to solve the issue for myself. Sadly I can't help with writing proper styles to support Arc theme as I have no idea what changes would be required. 

If anyone will have similar issue there is my changed code:

```css
#workspacestodockDock.right .workspace-thumbnails {
    border-radius: 9px 0 0 9px;
    border-right: none;
    border-image: none;
}

#workspacestodockDock.left .workspace-thumbnails {
    border-radius: 0 3px 3px 0;
    border-left: none;
    border-image: none;
    padding-right: 12px;
    padding-left: 8px;
}

#workspacestodockDock.top .workspace-thumbnails {
    border-radius: 0 0 9px 9px;
    border-top: none;
    border-image: none;
}

#workspacestodockDock.bottom .workspace-thumbnails {
    border-radius: 9px 9px 0 0;
    border-bottom: none;
    border-image: none;
}
```

It gets rid of the Arc look but for me, it looks good enough. Better than seeing pixel breaks :D

[Preview](http://i.imgur.com/q8FPDTh.png)
