### ISSUE TITLE
Can't set dock background opacity

### ISSUE THREAD

**Issue by oblitum** [passingthru67/workspaces-to-dock#75]
### Linux Distribution version

Updated Arch Linux

### Gnome Shell version

3.22.2

### Extension version or branch

master at 4fa3331

### Description of the problem

I'm unable to set dock background opacity. I'm not sure whether there's anything in my theme setup that's blocking this, I'd really like to know how to style this background, in truth I just installed this nice extension to see whether it would allow me to do it. 

### Steps to reproduce the problem

Previously to this issue, I've opened a question on http://unix.stackexchange.com/questions/325256/how-to-change-style-of-gnome-3-workspace-dock-background about how to tweak the background style. The question contains all the details about it.

Specifically to reproduce the issue on my system:

- Change the dock background opacity value through the extension menu: nothing changes.
- Reload the shell with `Alt-F2 r`: nothing changes.

**Comment by oblitum** [comment]
I just discovered that when using the Default shell theme, the opacity setting works... finally!

So the issue changes a bit:

Why when using the Arc-Dark Shell theme, it doesn't work?

Previously to this I've tried to tweak many settings at `/usr/share/themes/Arc-Dark/gnome-shell/gnome-shell.css` and reload the shell but simply nothing changed.

**Comment by passingthru67** [comment]
Arc is one of those themes that uses svg images for the borders and backgrounds of the dock panels. Essential, the CSS property that changes the opacity has no effect on the svg image. Issue #74 has a workaround for the rounded corners, but I don't know of a workaround for the background.

**Comment by oblitum** [comment]
Thanks. I think I'll try to figure out any tweak with that information.

**Comment by passingthru67** [comment]
If you can isolate the css property that sets the Arc background, then you should be able to set the opacity directly in the css. Let me know if you find a solution.

**Comment by passingthru67** [comment]
Check out the themes/Arc/gnome-shell/common-assets/dash folder. It seems they're using the dash-left.svg and dash-right.svg for the workspaces dock also.

**Comment by oblitum** [comment]
I'm trying to change any setting at `/usr/share/themes/Arc-Dark/gnome-shell/gnome-shell.css` to see whether anything changes in the shell appearance after reload but nothing changes. I don't know whethe the shell setting are really coming from this file when I set the shell theme to Arc-Dark, sadly I don't know from where it could be coming from. I have no shell theme installed in my home directory, all settings coming from the Arch packages.

**Comment by oblitum** [comment]
Yeah, THANKS! I've removed the reference to that SVG images from the CSS I've pointed and this changed the dock :-)

**Comment by oblitum** [comment]
Let ask I question, since I'm a noob in Gnome/GTK styling...

The Arc-Dark shell theme (`/usr/share/themes/Arc-Dark/gnome-shell/gnome-shell.css`) has this code section:

```css
.workspace-thumbnails,
.workspace-thumbnails-left:rtl {
  padding-right: 7px;
  border-image: url("common-assets/dash/dash-right.svg") 9 9 9 9; }

.workspace-thumbnails:rtl,
.workspace-thumbnails-left {
  padding-left: 7px;
  border-image: url("common-assets/dash/dash-left.svg") 9 9 9 9; }
```

Do you know whether I can override it from `~/.config/gtk-3.0/gtk.css`? I've tried to add there:

```css
.workspace-thumbnails,
.workspace-thumbnails-left:rtl {
    border-image: none;
}

.workspace-thumbnails:rtl,
.workspace-thumbnails-left {
    border-image: none;
}
```

But it didn't work.
